### PR TITLE
#163377772 include column title in the view pages 

### PR DESCRIPTION
**Pull request by Chiazokam**
#### What does this PR do?
This PR includes a title header to describe the columns in the view pages.

#### Description of Task to be completed?
- include column title in the view pages
- reduce the height of the party logo in mobile
- reposition the submit button on the vote page
- modify the hover color of text on the vote submit button
- make pages mobile responsive

#### How should this be manually tested?
- Clone the repo - `https://github.com/Chiazokam/Politico`
- Enter into the project directory - `cd Politico`
- switch to this branch - `checkout ft-ui-column-title-163377772`
- open the index.html file on the browser and navigate to the desired pages

#### What are the relevant pivotal tracker stories?
[#163377772](https://www.pivotaltracker.com/story/show/163377772)

### CODE REVIEW

**Comment by JCanaks** [comment]
@Chiazokam Please follow the convention for PR titles as mentioned earlier

**Comment by JCanaks** [comment]
Great work. I commend the effort taken. A few feedbacks. 
- Pls work on the title columns in the view pages. Reduce the height and pls change the color. 
- Also work on the mobile responsiveness of the pages
- Pls link your Politico logo to the home page

**Comment by JCanaks** [comment]
@Chiazokam You are still yet to correct the title description for this PR

**Comment by Chiazokam** [comment]
> @Chiazokam You are still yet to correct the title description for this PR

Corrected now. I thought it was for the next PRs.

**Comment by JCanaks** [comment]
Nice work on this, just a few feedbacks and you will be good to go with this PR:
- In the pages where you are viewing parties, offices and votes remove the 'View party', 'View office', 'View votes' and then just make the red banner thin like in the menu pages
- In the view votes page, reduce the font size of the office column on mobile view
- Remove the shadows that appears in the column title for some pages

**Comment by Chiazokam** [comment]
> Nice work on this, just a few feedbacks and you will be good to go with this PR:
> 
> * In the pages where you are viewing parties, offices and votes remove the 'View party', 'View office', 'View votes' and then just make the red banner thin like in the menu pages
> * In the view votes page, reduce the font size of the office column on mobile view
> * Remove the shadows that appears in the column title for some pages

Alright... Thanks.

**Comment by JCanaks** [comment]
@Chiazokam In addition feedback above for the. 
- For View offices pages instead of having just `Vote` there. You can have a more descriptive message like `Vote a candidate for an office` in smaller text and then reduce the red banner.
- Reduce the font size of your texts on the view pages for mobile view. 
- On mobile view, the column Title for the 'View office' and 'View votes' should be replaced with one descriptive title like 'Vote Candidates' for the `View offices` and `Votes` for the `View votes page`

**Comment by Chiazokam** [comment]
> @Chiazokam In addition feedback above for the.
> 
> * For View offices pages instead of having just `Vote` there. You can have a more descriptive message like `Vote a candidate for an office` in smaller text and then reduce the red banner.
> * Reduce the font size of your texts on the view pages for mobile view.
> * On mobile view, the column Title for the 'View office' and 'View votes' should be replaced with one descriptive title like 'Vote Candidates' for the `View offices` and `Votes` for the `View votes page`

Hi Jane,
Please I don't seem to understand:
image

Do I remove this strip above from ALL the view pages and replace with a thin strip?
Like this?

image

**Comment by Chiazokam** [comment]
> Nice work on this, just a few feedbacks and you will be good to go with this PR:
> 
> * In the pages where you are viewing parties, offices and votes remove the 'View party', 'View office', 'View votes' and then just make the red banner thin like in the menu pages
> * In the view votes page, reduce the font size of the office column on mobile view
> * Remove the shadows that appears in the column title for some pages

* I have removed the texts at the top and replaced with a thinner strip
* I have removed the 'bold' from the texts and reduces the font of the titles
* I have removed the shadow in the column titles

**Pull request merged**
