### PR TITLE
#163683565 consume the create party endpoint

### PR DESCRIPTION
**Pull request by Chiazokam**
#### What does this PR do?
This PR consumes the create party endpoint

#### Description of Task to be completed?
- consume the create party route
- display errors in a div
- define the url in use in the helpers file
- display the success message in a div

#### How should this be manually tested?
- Clone the repo - `https://github.com/Chiazokam/Politico`
- Enter into the project directory - `cd Politico`
- switch to this branch - `checkout ft-fetch-create-party-163683565`
- Start the server `npm run start:dev`
- Go to the `frontend` folder and run the index.html file on the browser
- Navigate to the create party page

#### Any background context you want to provide?
Nil

#### What are the relevant pivotal tracker stories?
[#163683565](https://www.pivotaltracker.com/story/show/163683565)

### CODE REVIEW

**Review by andela-gike — CHANGES_REQUESTED** [review]
Your PR has merge conflict, where do you branch out from when creating a new branch?

**Comment by Chiazokam** [comment]
> Your PR has merge conflict, where do you branch out from when creating a new branch?

I branched out from the feature branch because of the changes made there.

**Comment by Chiazokam** [comment]
> > Your PR has merge conflict, where do you branch out from when creating a new branch?
> 
> I branched out from the feature branch because of the changes made there.

Is that ok?
I'll resolve the conflicts before merging...

**Comment by andela-gike** [comment]
Best practices suggest we always branch out of develop before creating a new branch.

**Comment by Chiazokam** [comment]
> Best practices suggest we always branch out of develop before creating a new branch.

Alright...thanks...will be branching from the develop henceforth

**Review by andela-gike — APPROVED** [review]

**Pull request merged**
